default_platform(:android)

platform :android do
  desc "Build APK on code push"
  lane :build_apk do
    gradle(task: 'clean', project_dir: './android')
    gradle(
      task: 'assemble',
      build_type: 'Release',
      project_dir: './android'
    )
  end
end
